<?php
namespace Scribe;

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */


final class ResultCode {
  const OK = 0;
  const TRY_LATER = 1;
  static public $__names = array(
    0 => 'OK',
    1 => 'TRY_LATER',
  );
}



